apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "nginx 1.16"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "upgrade nginx to 1.17"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
