apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  labels:
    app: messaging
    tier: msg
spec:
  selector:
    app: messaging
    tier: msg
  ports:
    - protocol: TCP
      port: 6379
  type: ClusterIP